# .streamlit/secrets.toml
SNOWFLAKE_ACCOUNT = ""chewy-chewy""
SNOWFLAKE_USER = "yyikyong@chewy.com"
SNOWFLAKE_ROLE = "SC_USER"
SNOWFLAKE_WAREHOUSE = "SC_WH"
SNOWFLAKE_DATABASE = "EDLDB"
SNOWFLAKE_SCHEMA = "SC_REPLENISHMENT_SANDBOX"

# Auth: pick ONE approach
AUTHENTICATOR = "externalbrowser"   # if you use SSO
# AUTHENTICATOR = "snowflake"       # if using username/password
# SNOWFLAKE_PASSWORD = "..."        # only if using password
